/*
 * <CM5 charge-model tables (tblite)>
 * Copyright (C) 2019 - 2026 Conrad Hübler <Conrad.Huebler@gmx.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * AUTO-GENERATED by scripts/extract_tblite_cm5.py — DO NOT EDIT.
 * Source: tblite cm5.f90 + data/atomicrad.f90.
 *
 * CM5 (Charge Model 5) atomic parameters and atomic radii, used by the native
 * GFN1-xTB ALPB/GBSA solvation path: the Born matrix and CDS H-bond are
 * contracted with q_solute = q_Mulliken + cm5(geometry). The cm5 correction is
 * geometry-only (independent of the SCF charges).
 * Reference: Marenich, Cramer, Truhlar, J. Chem. Theory Comput. 2012, 8, 527.
 */

#pragma once

namespace curcuma {
namespace solvation {

// CM5 width parameter (1/Angstrom in the paper). Divide by AA_TO_AU (Bohr/Angstrom)
// at use to obtain 1/Bohr, matching tblite: cm5_alpha = 2.4740_wp / aatoau.
inline constexpr double cm5_alpha_per_aa = 2.4740;

inline const double cm5_a0[118] = {
     0.0056, -0.1543,  0.0000,  0.0333, -0.1030, -0.0446,
    -0.1072, -0.0802, -0.0629, -0.1088,  0.0184,  0.0000,
    -0.0726, -0.0790, -0.0756, -0.0565, -0.0444, -0.0767,
     0.0130,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
     0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
    -0.0512, -0.0557, -0.0533, -0.0399, -0.0313, -0.0541,
     0.0092,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
     0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
    -0.0361, -0.0393, -0.0376, -0.0281, -0.0220, -0.0381,
     0.0065,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
     0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
     0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
     0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
     0.0000,  0.0000, -0.0255, -0.0277, -0.0265, -0.0198,
    -0.0155, -0.0269,  0.0046,  0.0000,  0.0000,  0.0000,
     0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
     0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
     0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
     0.0000,  0.0000,  0.0000,  0.0000, -0.0179, -0.0195,
    -0.0187, -0.0140, -0.0110, -0.0189,
};

// Atomic radii (Angstrom) from tblite data/atomicrad.f90; multiply by
// CurcumaUnit::AA_TO_AU for Bohr.
inline const double cm5_atomic_rad_aa[118] = {
     0.3200,  0.3700,  1.3000,  0.9900,  0.8400,  0.7500,
     0.7100,  0.6400,  0.6000,  0.6200,  1.6000,  1.4000,
     1.2400,  1.1400,  1.0900,  1.0400,  1.0000,  1.0100,
     2.0000,  1.7400,  1.5900,  1.4800,  1.4400,  1.3000,
     1.2900,  1.2400,  1.1800,  1.1700,  1.2200,  1.2000,
     1.2300,  1.2000,  1.2000,  1.1800,  1.1700,  1.1600,
     2.1500,  1.9000,  1.7600,  1.6400,  1.5600,  1.4600,
     1.3800,  1.3600,  1.3400,  1.3000,  1.3600,  1.4000,
     1.4200,  1.4000,  1.4000,  1.3700,  1.3600,  1.3600,
     2.3800,  2.0600,  1.9400,  1.8400,  1.9000,  1.8800,
     1.8600,  1.8500,  1.8300,  1.8200,  1.8100,  1.8000,
     1.7900,  1.7700,  1.7700,  1.7800,  1.7400,  1.6400,
     1.5800,  1.5000,  1.4100,  1.3600,  1.3200,  1.3000,
     1.3000,  1.3200,  1.4400,  1.4500,  1.5000,  1.4200,
     1.4800,  1.4600,  2.4200,  2.1100,  2.0100,  1.9000,
     1.8400,  1.8300,  1.8000,  1.8000,  1.7300,  1.6800,
     1.6800,  1.6800,  1.6500,  1.6700,  1.7300,  1.7600,
     1.6100,  1.5700,  1.4900,  1.4300,  1.4100,  1.3400,
     1.2900,  1.2800,  1.2100,  1.2200,  1.3600,  1.4300,
     1.6200,  1.7500,  1.6500,  1.5700,
};

// Element-pair parameter overrides (Fortran 1-based Z): pairpar(Zi,Zj).
// pairpar(Zi,Zj) defaults to cm5_a0[Zi-1]-cm5_a0[Zj-1]; these pairs override it,
// and pairpar(Zj,Zi) = -pairpar(Zi,Zj). (cm5.f90:89-94)
struct Cm5PairOverride { int zi; int zj; double pij; };
inline const Cm5PairOverride cm5_pair_overrides[6] = {
    {1, 6,  0.0502},
    {1, 7,  0.1747},
    {1, 8,  0.1671},
    {6, 7,  0.0556},
    {6, 8,  0.0234},
    {7, 8, -0.0346},
};

} // namespace solvation
} // namespace curcuma
