#include <algorithm>
#include <fstream>
#include <iostream>
#include <map>
#include <regex>
#include <sstream>
#include <string>
#include <vector>

// Data structure to hold a parsed parameter definition
struct Parameter {
    std::string module;
    std::string name;
    std::string type;
    std::string defaultValue;
    std::string helpText;
    std::string category;
    std::string aliases;
    std::string annotation;  // Claude Generated 2026 - optional 7th argument
};

// Claude Generated 2026 - What a module IS, from MODULE_INFO.
struct Module {
    std::string name;
    std::string description;
    std::string category;
    std::string commands;  // raw brace contents, parsed like aliases
};

/// Split a brace list of quoted strings ({"a", "b"}) into its entries.
std::vector<std::string> split_quoted_list(const std::string& raw)
{
    std::vector<std::string> out;
    std::string current;
    bool in_quotes = false;
    for (char c : raw) {
        if (c == '"') {
            in_quotes = !in_quotes;
        } else if (c == ',' && !in_quotes) {
            if (!current.empty())
                out.push_back(current);
            current.clear();
        } else if (in_quotes) {
            current += c;
        }
    }
    if (!current.empty())
        out.push_back(current);
    return out;
}

/// Parse "tier=primary; enum=a|b; unit=K" into its pairs. Keys without a value
/// (e.g. "deprecated") map to an empty string.
std::map<std::string, std::string> parse_annotation(const std::string& text)
{
    std::map<std::string, std::string> out;
    std::stringstream ss(text);
    std::string item;
    while (std::getline(ss, item, ';')) {
        const size_t begin = item.find_first_not_of(" \t");
        if (begin == std::string::npos)
            continue;
        const size_t end = item.find_last_not_of(" \t");
        item = item.substr(begin, end - begin + 1);
        const size_t eq = item.find('=');
        if (eq == std::string::npos)
            out[item] = "";
        else
            out[item.substr(0, eq)] = item.substr(eq + 1);
    }
    return out;
}

// Function to trim leading/trailing whitespace and quotes
std::string trim(const std::string& str)
{
    const std::string whitespace = " \t\"";
    const auto strBegin = str.find_first_not_of(whitespace);
    if (strBegin == std::string::npos)
        return "";
    const auto strEnd = str.find_last_not_of(whitespace);
    const auto strRange = strEnd - strBegin + 1;
    return str.substr(strBegin, strRange);
}

/// Is the PARAM( ... ) of @p text closed?
///
/// Claude Generated 2026 - The accumulator used to give up as soon as the text so
/// far held "PARAM" and any ')'. Help texts contain those long before the PARAM's
/// own closing paren -- "'chloroform'). 'none' (default)" is enough -- so a PARAM
/// written across several lines with adjacent string literals was warned about and
/// then thrown away. gfnff's `solvent` and `solvent_model` were lost that way and
/// never reached the registry, which is why the source carries a note asking for
/// PARAMs to stay on one line.
///
/// Parentheses inside string literals do not count, and a backslash escapes the
/// next character.
bool param_parens_closed(const std::string& text)
{
    bool in_string = false;
    bool escaped = false;
    bool saw_open = false;
    int depth = 0;

    for (char c : text) {
        if (escaped) {
            escaped = false;
            continue;
        }
        if (c == '\\') {
            escaped = true;
            continue;
        }
        if (c == '"') {
            in_string = !in_string;
            continue;
        }
        if (in_string)
            continue;
        if (c == '(') {
            ++depth;
            saw_open = true;
        } else if (c == ')') {
            --depth;
        }
    }
    return saw_open && depth <= 0;
}

// Function to generate the C++ header file content - Claude Generated (fixed)
std::string generate_header_content(const std::vector<Parameter>& params,
                                    const std::vector<Module>& modules)
{
    std::stringstream ss;
    ss << "// THIS FILE IS AUTO-GENERATED BY curcuma_param_parser. DO NOT EDIT MANUALLY.\n\n";
    ss << "#pragma once\n";
    ss << "#include \"src/core/parameter_registry.h\"\n";
    ss << "#include <string>\n\n";
    ss << "// This function will be called to populate the registry\n";
    ss << "inline void initialize_generated_registry() {\n";
    ss << "    auto& registry = ParameterRegistry::getInstance();\n\n";

    // Claude Generated 2026 - Module metadata first, so a consumer can ask what a
    // module is before asking what it contains.
    for (const auto& m : modules) {
        ss << "    {\n";
        ss << "        ModuleDefinition m;\n";
        ss << "        m.name = \"" << m.name << "\";\n";
        ss << "        m.description = \"" << m.description << "\";\n";
        ss << "        m.category = \"" << m.category << "\";\n";
        for (const auto& command : split_quoted_list(m.commands))
            ss << "        m.commands.push_back(\"" << command << "\");\n";
        ss << "        registry.addModule(std::move(m));\n";
        ss << "    }\n";
    }
    if (!modules.empty())
        ss << "\n";

    for (const auto& p : params) {
        // Claude Generated 2026 - A named block rather than a positional aggregate:
        // the definition grew optional fields, and adding them positionally would
        // mean emitting every one of them for every parameter just to reach the
        // last.
        ss << "    {\n";
        ss << "        ParameterDefinition d;\n";
        ss << "        d.name = \"" << p.name << "\";\n";
        ss << "        d.module = \"" << p.module << "\";\n";
        ss << "        d.type = ParamType::" << p.type << ";\n";

        if (p.type == "String" || p.type == "Selection" || p.type == "Path"
            || p.type == "StringList" || p.type == "Json") {
            ss << "        d.defaultValue = std::string(\"" << p.defaultValue << "\");\n";
        } else {
            ss << "        d.defaultValue = " << p.defaultValue << ";\n";
        }

        ss << "        d.helpText = \"" << p.helpText << "\";\n";
        ss << "        d.category = \"" << p.category << "\";\n";
        for (const auto& alias : split_quoted_list(p.aliases))
            ss << "        d.aliases.push_back(\"" << alias << "\");\n";

        if (!p.annotation.empty()) {
            const auto fields = parse_annotation(p.annotation);
            for (const auto& field : fields) {
                const std::string& key = field.first;
                const std::string& value = field.second;
                if (key == "tier") {
                    const std::string tier = value == "primary" ? "Primary"
                        : value == "expert"                     ? "Expert"
                                                                : "Advanced";
                    ss << "        d.tier = ParamTier::" << tier << ";\n";
                } else if (key == "enum") {
                    std::stringstream values(value);
                    std::string one;
                    while (std::getline(values, one, '|')) {
                        if (!one.empty())
                            ss << "        d.allowed.push_back(\"" << one << "\");\n";
                    }
                } else if (key == "unit") {
                    ss << "        d.unit = \"" << value << "\";\n";
                } else if (key == "min") {
                    ss << "        d.hasMinimum = true; d.minimum = " << value << ";\n";
                } else if (key == "max") {
                    ss << "        d.hasMaximum = true; d.maximum = " << value << ";\n";
                } else if (key == "requires") {
                    ss << "        d.relevantWhen = \"" << value << "\";\n";
                } else if (key == "deprecated") {
                    ss << "        d.deprecated = true;\n";
                } else if (key == "replaced_by") {
                    ss << "        d.replacedBy = \"" << value << "\";\n";
                } else {
                    std::cerr << "Warning: unknown annotation key \"" << key
                              << "\" on " << p.module << "." << p.name << "\n";
                }
            }
        }

        ss << "        registry.addDefinition(\"" << p.module << "\", std::move(d));\n";
        ss << "    }\n";
    }

    ss << "}\n";
    return ss.str();
}

int main(int argc, char* argv[])
{
    std::vector<std::string> input_files;
    std::string output_file;

    // 1. Parse command-line arguments
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "--inputs" && i + 1 < argc) {
            // Collect all subsequent arguments as input files until another flag is found
            while (i + 1 < argc && argv[i + 1][0] != '-') {
                input_files.push_back(argv[++i]);
            }
        } else if (arg == "--output" && i + 1 < argc) {
            output_file = argv[++i];
        }
    }

    if (output_file.empty()) {
        std::cerr << "Error: --output file path not specified." << std::endl;
        return 1;
    }
    if (input_files.empty()) {
        std::cerr << "Warning: No --inputs specified." << std::endl;
    }

    // 2. Parse all input files
    std::vector<Parameter> all_params;
    std::vector<Module> all_modules;
    std::regex begin_regex(R"(BEGIN_PARAMETER_DEFINITION\s*\(\s*(\w+)\s*\))");
    std::regex end_regex(R"(END_PARAMETER_DEFINITION)");
    // Fixed regex: \"s* → \"\s* (typo fix), added multiline support
    // Claude Generated 2026 - the trailing group is the optional annotation string.
    std::regex param_regex(R"(PARAM\s*\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(.*?)\s*,\s*\"(.*?)\"\s*,\s*\"(.*?)\"\s*,\s*\{(.*?)\}(?:\s*,\s*\"([^\"]*)\")?\s*\))", std::regex::ECMAScript);
    std::regex module_info_regex(R"(MODULE_INFO\s*\(\s*\"(.*?)\"\s*,\s*\"(.*?)\"\s*,\s*\{(.*?)\}\s*\))", std::regex::ECMAScript);

    bool in_param_block = false;
    std::string current_module;

    for (const auto& filepath : input_files) {
        // Claude Generated (October 2025): Skip parameter_macros.h - it contains macro definitions only, not parameter declarations
        if (filepath.find("parameter_macros.h") != std::string::npos) {
            continue;
        }

        std::ifstream file(filepath);
        if (!file.is_open()) {
            std::cerr << "Warning: Could not open file " << filepath << "\n";
            continue;
        }

        // Read entire file content for multi-line PARAM support - Claude Generated
        std::string file_content((std::istreambuf_iterator<char>(file)),
            std::istreambuf_iterator<char>());
        file.close();

        std::string line;
        std::istringstream stream(file_content);
        int line_number = 0;
        std::string accumulated_line;

        while (std::getline(stream, line)) {
            line_number++;
            std::smatch match;

            // Check for BEGIN block
            if (std::regex_search(line, match, begin_regex)) {
                in_param_block = true;
                current_module = match[1];
                accumulated_line.clear();
                continue;
            }

            // Check for END block
            if (std::regex_search(line, match, end_regex)) {
                in_param_block = false;
                current_module = "";
                accumulated_line.clear();
                continue;
            }

            if (in_param_block) {
                // Claude Generated 2026 - module metadata, one line, before the params.
                if (std::regex_search(line, match, module_info_regex) && match.size() == 4) {
                    all_modules.push_back({ current_module, trim(match[1]), trim(match[2]),
                        std::string(match[3]) });
                    continue;
                }

                // A comment line is not a declaration. gfnff.h keeps a removed
                // parameter as "// PARAM(eeq_distance_cutoff, ...) - REMOVED" for
                // the record, and without this it is reported as malformed on
                // every single build.
                const std::string stripped = line.substr(line.find_first_not_of(" \t") == std::string::npos
                        ? 0
                        : line.find_first_not_of(" \t"));
                if (stripped.rfind("//", 0) == 0)
                    continue;

                // Ignore anything before a PARAM starts: comments between the
                // definitions would otherwise end up glued to the next one.
                if (accumulated_line.empty() && line.find("PARAM(") == std::string::npos)
                    continue;

                // Accumulate lines for multi-line PARAM definitions
                accumulated_line += " " + line;

                // Wait until the PARAM's own parenthesis is closed. Judging by the
                // mere presence of ')' cuts multi-line definitions in half (see
                // param_parens_closed).
                if (!param_parens_closed(accumulated_line))
                    continue;

                // Try to match complete PARAM definition
                if (std::regex_search(accumulated_line, match, param_regex) && match.size() == 8) {
                    all_params.push_back({
                        current_module,
                        trim(match[1]), // name
                        trim(match[2]), // type
                        trim(match[3]), // defaultValue
                        trim(match[4]), // helpText
                        trim(match[5]), // category
                        std::string(match[6]), // aliases - DON'T trim! We need quotes for parsing
                        std::string(match[7])  // annotation, empty when absent
                    });
                    accumulated_line.clear();
                } else {
                    // Closed, but still no match: a genuine syntax error rather
                    // than a definition that had not finished arriving.
                    std::cerr << "Warning: Malformed PARAM in " << filepath
                              << " around line " << line_number << "\n";
                    accumulated_line.clear();
                }
            }
        }
    }

    // 3. Generate the header file content
    std::string header_content = generate_header_content(all_params, all_modules);

    // 4. Write the output file
    std::ofstream out(output_file);
    if (!out.is_open()) {
        std::cerr << "Error: Could not open output file " << output_file << " for writing." << std::endl;
        return 1;
    }
    out << header_content;
    out.close();

    std::cout << "Successfully generated " << output_file << " with " << all_params.size() << " parameter definitions and " << all_modules.size() << " module descriptions." << std::endl;

    return 0;
}
