/*
 * rev-gfnff stage 3a(iii): per-element-pair parameters of the two curvature-pinned bond-well
 * forms.  GENERATED by scripts/revgfnff_wellfit.py - do not edit by hand.
 *
 * AI-FITTED (Claude Generated, Sep 2026), machine-tested only.  Source: the class-A reference
 * scans under test_cases/revgfnff/ref/A/ (r2SCAN-3c, merged min(RKS, UKS) with the QUALITY.md
 * exclusions), fitted on the BREAK side against the CHARGE-FROZEN rest of the molecule.  Per
 * element pair the value is the MEDIAN over the class-A systems that carry that pair.
 *
 * s    = D / |k_b|, the depth scale on the delivered Gaussian's own force constant
 * tail = beta (MG, 1/Angstrom^2) or sigma (erf-Morse, Angstrom)
 *
 * Binary that produced the scans: md5 01e9b4e6862f8558a28a0f51e67f5e42, rest qfrozen.
 */
#pragma once

#include <cstddef>

namespace RevWellTable {

struct Entry {
    int z1, z2;
    double mg_s, mg_beta;
    double em_s, em_sigma;
};

static constexpr Entry kEntries[] = {
    {  6,  6,   1.007711,   0.563871,   1.006843,   1.151365 },   // C-C (n = 3)
    {  6, 17,   1.573974,   0.520653,   1.571482,   1.190326 },   // C-Cl (n = 1)
    {  6,  9,   1.356148,   0.380106,   1.354879,   1.465391 },   // C-F (n = 1)
    {  1,  6,   1.024953,   0.521506,   1.022722,   1.230565 },   // H-C (n = 2)
    {  6,  7,   0.818790,   1.049199,   0.817368,   0.838998 },   // C-N (n = 3)
    {  6,  8,   1.480242,   0.563336,   1.477256,   1.155672 },   // C-O (n = 3)
    { 17, 17,   2.356528,   1.434449,   2.352517,   0.647060 },   // Cl-Cl (n = 1)
    {  9, 17,   1.209528,   2.302143,   1.201427,   0.516633 },   // F-Cl (n = 1)
    {  1, 17,   1.816866,   1.264191,   1.812170,   0.714466 },   // H-Cl (n = 1)
    {  7, 17,   0.671732,   0.318183,   0.671475,   1.643558 },   // N-Cl (n = 1)
    {  8, 17,   0.911268,   1.700828,   0.907994,   0.624836 },   // O-Cl (n = 1)
    {  9,  9,   0.549139,  12.399401,   0.549108,   0.200894 },   // F-F (n = 1)
    {  1,  9,   1.585708,   1.475751,   1.581007,   0.680508 },   // H-F (n = 1)
    {  7,  9,   0.721646,   0.483015,   0.721298,   1.318112 },   // N-F (n = 1)
    {  8,  9,   0.458550,   3.233702,   0.456289,   0.453371 },   // O-F (n = 1)
    {  1,  1,   1.025038,   1.135472,   1.019882,   0.778512 },   // H-H (n = 1)
    {  1,  7,   1.028265,   0.991997,   1.025511,   0.852086 },   // H-N (n = 1)
    {  1,  8,   1.391530,   1.497516,   1.387421,   0.673406 },   // H-O (n = 2)
    {  7,  7,   0.682898,   1.628612,   0.681208,   0.649747 },   // N-N (n = 3)
    {  7,  8,   0.675823,   0.776284,   0.675046,   1.004562 },   // N-O (n = 1)
    {  8,  8,   0.933492,   0.671241,   0.932141,   1.077456 },   // O-O (n = 2)
};

static constexpr std::size_t kCount = sizeof(kEntries) / sizeof(kEntries[0]);

/// The entry for an element pair, or nullptr when the class-A set has no data for it - the
/// caller then falls back to the delivered Gaussian and says so at verbosity 2.
inline const Entry* find(int za, int zb)
{
    const int z1 = za < zb ? za : zb;
    const int z2 = za < zb ? zb : za;
    for (std::size_t k = 0; k < kCount; ++k)
        if (kEntries[k].z1 == z1 && kEntries[k].z2 == z2)
            return &kEntries[k];
    return nullptr;
}

} // namespace RevWellTable
