/*
 * rev-gfnff stage 3a(iii) step 2 + stage 3b: parameters of the FREE-CURVATURE MG bond well.
 * GENERATED by scripts/revgfnff_wellfit.py --form mg2 - do not edit by hand.
 *
 * AI-FITTED (Claude Generated, Sep 2026), machine-tested only.  Source: the class-A reference
 * scans under test_cases/revgfnff/ref/A/ (r2SCAN-3c, merged min(RKS, UKS) with the QUALITY.md
 * exclusions), fitted on the BREAK side against the CHARGE-FROZEN rest of the molecule.
 *
 * The form is the same MG well as rev_well_table.h,
 *
 *     E = -D (2 y - y^2),   y = exp(-(a x + beta x^2)),   x = r - (r0_model + dr0),
 *
 * but with FOUR free parameters per key instead of two - the curvature at the minimum and the
 * position of the minimum are no longer inherited from the delivered Gaussian:
 *
 *   s    = D / |k_b|                     depth scale on the delivered force constant
 *   ca   = a / sqrt(alpha / s)           CURVATURE scale; the curvature at the minimum is
 *                                        K = 2 D a^2 = ca^2 * (2 alpha |k_b|), so ca = 1 is
 *                                        exactly the curvature-pinned table (rev_well_table.h)
 *   beta = the MG tail parameter [1/Angstrom^2]
 *   dr0  = the r0 RE-SOLVE [Angstrom], an offset ON TOP of the model's own dynamic r0, so the
 *          stage-3a(i) CN dependence of r0 is preserved and only its class-A offset is fitted
 *
 * ca = 1, dr0 = 0 reproduces rev_well_table.h's mg entry bit-for-bit, which is how the code path
 * was verified before the free-curvature fit was run.
 *
 * Binary that produced the scans: md5 dc1bbd90ff5ef83a5b6a3a01a511de20, rest qfrozen.
 *
 * kPairEntries is keyed on the ELEMENT PAIR (well form 'mg2'); kOrderEntries adds the nominal
 * bond ORDER (1/2/3) and is interpolated at runtime on the CONTINUOUS order Bond::rev_order
 * (well form 'mg3').
 */
#pragma once

#include <cstddef>

namespace RevWellTableV2 {

struct Entry {
    int z1, z2;
    double s, ca, beta, dr0;
};

struct OrderEntry {
    int z1, z2;
    int order;                 ///< nominal bond order of the class-A system this row was fitted on
    double s, ca, beta, dr0;
};

static constexpr Entry kPairEntries[] = {
    {  6,  6,   1.009398,   1.184251,   0.352874,   0.033237 },   // C-C (n = 3, fit rms 3.60)
    {  6, 17,   1.540973,   1.320348,   0.426292,   0.124875 },   // C-Cl (n = 1, fit rms 1.04)
    {  6,  9,   1.293540,   1.076112,   0.644826,   0.131122 },   // C-F (n = 1, fit rms 2.47)
    {  1,  6,   1.030660,   1.063125,   0.432171,   0.002198 },   // C-H (n = 2, fit rms 0.78)
    {  6,  7,   0.800995,   1.227120,   0.897179,   0.068449 },   // C-N (n = 3, fit rms 2.29)
    {  6,  8,   1.441943,   1.211688,   0.472717,   0.066592 },   // C-O (n = 3, fit rms 8.45)
    { 17, 17,   2.360922,   1.854655,   0.734334,   0.029828 },   // Cl-Cl (n = 1, fit rms 9.53)
    {  9, 17,   1.170167,   1.544609,   2.551371,   0.108797 },   // Cl-F (n = 1, fit rms 1.19)
    {  1, 17,   1.845786,   1.577804,   0.486186,   0.007254 },   // Cl-H (n = 1, fit rms 2.46)
    {  7, 17,   0.636263,   0.300000,   1.385955,  -0.046140 },   // Cl-N (n = 1, fit rms 1.19)
    {  8, 17,   0.868520,   1.523319,   1.872198,   0.137170 },   // Cl-O (n = 1, fit rms 1.27)
    {  9,  9,   0.550657,   1.962998,   3.720819,  -0.027992 },   // F-F (n = 1, fit rms 0.48)
    {  1,  9,   1.643992,   1.229057,   0.778970,  -0.028521 },   // F-H (n = 1, fit rms 2.14)
    {  7,  9,   0.672592,   0.958384,   1.100942,   0.116426 },   // F-N (n = 1, fit rms 1.85)
    {  8,  9,   0.445930,   1.318037,   3.443174,   0.062207 },   // F-O (n = 1, fit rms 1.47)
    {  1,  1,   1.186460,   1.114444,   0.326230,  -0.174329 },   // H-H (n = 1, fit rms 2.92)
    {  1,  7,   1.018052,   1.142257,   0.896425,   0.038398 },   // H-N (n = 1, fit rms 0.96)
    {  1,  8,   1.422789,   1.224739,   0.986362,  -0.014134 },   // H-O (n = 2, fit rms 3.10)
    {  7,  7,   0.636968,   1.186609,   1.698023,   0.110107 },   // N-N (n = 3, fit rms 2.11)
    {  7,  8,   0.633875,   1.315561,   0.711070,   0.143563 },   // N-O (n = 1, fit rms 1.15)
    {  8,  8,   0.882680,   1.064531,   1.691750,   0.112260 },   // O-O (n = 2, fit rms 8.63)
};

static constexpr std::size_t kPairCount = sizeof(kPairEntries) / sizeof(kPairEntries[0]);

static constexpr OrderEntry kOrderEntries[] = {
    {  1,  1, 1,   1.186460,   1.114444,   0.326230,  -0.174329 },   // H-H order 1 (n = 1, h2_H-H, fit rms 2.92)
    {  1,  6, 1,   1.030660,   1.063125,   0.432171,   0.002198 },   // C-H order 1 (n = 2, ch4_C-H+hcn_HC-H, fit rms 0.78)
    {  1,  7, 1,   1.018052,   1.142257,   0.896425,   0.038398 },   // H-N order 1 (n = 1, nh3_N-H, fit rms 0.96)
    {  1,  8, 1,   1.422789,   1.224739,   0.986362,  -0.014134 },   // H-O order 1 (n = 2, ch3oh_HO-H+h2o_O-H, fit rms 3.10)
    {  1,  9, 1,   1.643992,   1.229057,   0.778970,  -0.028521 },   // F-H order 1 (n = 1, hf_H-F, fit rms 2.14)
    {  1, 17, 1,   1.845786,   1.577804,   0.486186,   0.007254 },   // Cl-H order 1 (n = 1, hcl_H-Cl, fit rms 2.46)
    {  6,  6, 1,   1.172113,   1.258156,   0.352874,   0.055841 },   // C-C order 1 (n = 1, c2h6_C-C, fit rms 0.85)
    {  6,  6, 2,   1.009398,   1.184251,   0.279188,   0.033237 },   // C-C order 2 (n = 1, c2h4_CDC, fit rms 3.60)
    {  6,  6, 3,   0.908934,   1.024906,   0.868506,  -0.003408 },   // C-C order 3 (n = 1, c2h2_CTC, fit rms 8.27)
    {  6,  7, 1,   0.976610,   1.330789,   0.613927,   0.078087 },   // C-N order 1 (n = 1, ch3nh2_C-N, fit rms 0.46)
    {  6,  7, 2,   0.798420,   1.227120,   0.897179,   0.068449 },   // C-N order 2 (n = 1, ch2nh_CDN, fit rms 2.29)
    {  6,  7, 3,   0.800995,   1.052881,   1.110581,   0.008294 },   // C-N order 3 (n = 1, hcn_CTN, fit rms 7.92)
    {  6,  8, 1,   1.087798,   1.300313,   0.503879,   0.066592 },   // C-O order 1 (n = 1, ch3oh_C-O, fit rms 2.41)
    {  6,  8, 2,   1.441943,   1.211688,   0.472717,   0.085735 },   // C-O order 2 (n = 1, h2co_CDO, fit rms 9.57)
    {  6,  8, 3,   1.466511,   0.998127,   0.437568,   0.046696 },   // C-O order 3 (n = 1, co_CTO, fit rms 8.45)
    {  6,  9, 1,   1.293540,   1.076112,   0.644826,   0.131122 },   // C-F order 1 (n = 1, ch3f_C-F, fit rms 2.47)
    {  6, 17, 1,   1.540973,   1.320348,   0.426292,   0.124875 },   // C-Cl order 1 (n = 1, ch3cl_C-Cl, fit rms 1.04)
    {  7,  7, 1,   0.597782,   1.253018,   1.381088,   0.199961 },   // N-N order 1 (n = 1, n2h4_N-N, fit rms 1.27)
    {  7,  7, 2,   0.636968,   1.075029,   3.109856,   0.110107 },   // N-N order 2 (n = 1, n2h2_NDN, fit rms 2.11)
    {  7,  7, 3,   0.809306,   1.186609,   1.698023,  -0.012700 },   // N-N order 3 (n = 1, n2_NTN, fit rms 2.16)
    {  7,  8, 1,   0.633875,   1.315561,   0.711070,   0.143563 },   // N-O order 1 (n = 1, nh2oh_N-O, fit rms 1.15)
    {  7,  9, 1,   0.672592,   0.958384,   1.100942,   0.116426 },   // F-N order 1 (n = 1, nf3_N-F, fit rms 1.85)
    {  7, 17, 1,   0.636263,   0.300000,   1.385955,  -0.046140 },   // Cl-N order 1 (n = 1, ncl3_N-Cl, fit rms 1.19)
    {  8,  8, 1,   1.167113,   1.341020,   0.209528,  -0.010912 },   // O-O order 1 (n = 1, h2o2_O-O, fit rms 13.41)
    {  8,  8, 3,   0.598248,   0.788043,   3.173972,   0.235432 },   // O-O order 3 (n = 1, o2_ODO, fit rms 3.86)
    {  8,  9, 1,   0.445930,   1.318037,   3.443174,   0.062207 },   // F-O order 1 (n = 1, of2_O-F, fit rms 1.47)
    {  8, 17, 1,   0.868520,   1.523319,   1.872198,   0.137170 },   // Cl-O order 1 (n = 1, hocl_O-Cl, fit rms 1.27)
    {  9,  9, 1,   0.550657,   1.962998,   3.720819,  -0.027992 },   // F-F order 1 (n = 1, f2_F-F, fit rms 0.48)
    {  9, 17, 1,   1.170167,   1.544609,   2.551371,   0.108797 },   // Cl-F order 1 (n = 1, clf_F-Cl, fit rms 1.19)
    { 17, 17, 1,   2.360922,   1.854655,   0.734334,   0.029828 },   // Cl-Cl order 1 (n = 1, cl2_Cl-Cl, fit rms 9.53)
};

static constexpr std::size_t kOrderCount = sizeof(kOrderEntries) / sizeof(kOrderEntries[0]);

/// The element-pair entry, or nullptr when the class-A set has no data for that pair - the
/// caller then falls back to the delivered Gaussian and says so at verbosity 2.
inline const Entry* find(int za, int zb)
{
    const int z1 = za < zb ? za : zb;
    const int z2 = za < zb ? zb : za;
    for (std::size_t k = 0; k < kPairCount; ++k)
        if (kPairEntries[k].z1 == z1 && kPairEntries[k].z2 == z2)
            return &kPairEntries[k];
    return nullptr;
}

/// The bond-order-resolved parameters of an element pair at a CONTINUOUS order, linearly
/// interpolated between the nominal orders the class-A set covers for that pair and CLAMPED at
/// the lowest / highest of them.  Returns false when the pair has no order row at all (the
/// caller then uses find() above, i.e. the element-pair fit).
///
/// The interpolation is Lipschitz in \p order and \p order is a topology constant inside one
/// energy call, so this introduces no geometry derivative and no switch: a pair whose pi order
/// drifts moves its well parameters proportionally, never in a step.  A pair the class-A set
/// covers at ONE order only (e.g. C-H, which has no double or triple member) returns that row
/// for every order, i.e. it behaves exactly like the element-pair table.
inline bool findOrder(int za, int zb, double order, double& s, double& ca, double& beta, double& dr0)
{
    const int z1 = za < zb ? za : zb;
    const int z2 = za < zb ? zb : za;
    const OrderEntry* lo = nullptr;
    const OrderEntry* hi = nullptr;
    for (std::size_t k = 0; k < kOrderCount; ++k) {
        const OrderEntry& e = kOrderEntries[k];
        if (e.z1 != z1 || e.z2 != z2)
            continue;
        const double o = static_cast<double>(e.order);
        if (o <= order && (!lo || o > static_cast<double>(lo->order)))
            lo = &e;
        if (o >= order && (!hi || o < static_cast<double>(hi->order)))
            hi = &e;
    }
    if (!lo && !hi)
        return false;
    if (!lo)
        lo = hi;                       // order below the lowest fitted one -> clamp
    if (!hi)
        hi = lo;                       // order above the highest fitted one -> clamp
    double t = 0.0;
    if (hi->order != lo->order)
        t = (order - static_cast<double>(lo->order))
            / static_cast<double>(hi->order - lo->order);
    s = lo->s + t * (hi->s - lo->s);
    ca = lo->ca + t * (hi->ca - lo->ca);
    beta = lo->beta + t * (hi->beta - lo->beta);
    dr0 = lo->dr0 + t * (hi->dr0 - lo->dr0);
    return true;
}

} // namespace RevWellTableV2
