/*
 * rev-gfnff stage 3a(iii) step 2 + stage 3b: parameters of the FREE-CURVATURE MG bond well.
 * GENERATED by scripts/revgfnff_wellfit.py --form mg2 - do not edit by hand.
 *
 * AI-FITTED (Claude Generated, Sep 2026), machine-tested only.  Source: the class-A reference
 * scans under test_cases/revgfnff/ref/A/ (r2SCAN-3c, merged min(RKS, UKS) with the QUALITY.md
 * exclusions), fitted on the BREAK side against the CHARGE-FROZEN rest of the molecule.
 *
 * The form is the same MG well as rev_well_table.h,
 *
 *     E = -D (2 y - y^2),   y = exp(-(a x + beta x^2)),   x = r - (r0_model + dr0),
 *
 * but with FOUR free parameters per key instead of two - the curvature at the minimum and the
 * position of the minimum are no longer inherited from the delivered Gaussian:
 *
 *   s    = D / |k_b|                     depth scale on the delivered force constant
 *   ca   = a / sqrt(alpha / s)           CURVATURE scale; the curvature at the minimum is
 *                                        K = 2 D a^2 = ca^2 * (2 alpha |k_b|), so ca = 1 is
 *                                        exactly the curvature-pinned table (rev_well_table.h)
 *   beta = the MG tail parameter [1/Angstrom^2]
 *   dr0  = the r0 RE-SOLVE [Angstrom], an offset ON TOP of the model's own dynamic r0, so the
 *          stage-3a(i) CN dependence of r0 is preserved and only its class-A offset is fitted
 *
 * ca = 1, dr0 = 0 reproduces rev_well_table.h's mg entry bit-for-bit, which is how the code path
 * was verified before the free-curvature fit was run.
 *
 * Binary that produced the scans: md5 7da448dd82c791f5840d3e70bc8e9ffb, rest qfrozen.
 *
 * kPairEntries is keyed on the ELEMENT PAIR (well form 'mg2'); kOrderEntries adds the nominal
 * bond ORDER (1/2/3) and is interpolated at runtime on the CONTINUOUS order Bond::rev_order
 * (well form 'mg3').
 */
#pragma once

#include <algorithm>
#include <cstddef>

namespace RevWellTableV2 {

struct Entry {
    int z1, z2;
    double s, ca, beta, dr0;
};

struct OrderEntry {
    int z1, z2;
    int order;                 ///< nominal bond order of the class-A system this row was fitted on
    double s, ca, beta, dr0;
};

static constexpr Entry kPairEntries[] = {
    {  6,  6,   1.001773,   1.184251,   0.343179,   0.046940 },   // C-C (n = 3, fit rms 3.89)
    {  6, 17,   1.545489,   1.320348,   0.383334,   0.110113 },   // C-Cl (n = 1, fit rms 0.80)
    {  6,  9,   1.306356,   1.076112,   0.501862,   0.096872 },   // C-F (n = 1, fit rms 1.55)
    {  1,  6,   1.031578,   1.063125,   0.426883,   0.000094 },   // C-H (n = 2, fit rms 0.77)
    {  6,  7,   0.815909,   1.227120,   0.814170,   0.053747 },   // C-N (n = 3, fit rms 1.83)
    {  6,  8,   1.467046,   1.211688,   0.401442,   0.049790 },   // C-O (n = 3, fit rms 4.65)
    { 17, 17,   1.825132,   1.854651,   1.235720,   0.034200 },   // Cl-Cl (n = 1, fit rms 1.07)
    { 35, 35,   1.183487,   1.224448,   1.021135,   0.067712 },   // Br-Br (n = 1, fit rms 0.79) X2BR:pair br2_Br-Br class-A r2SCAN-3c, hand-inserted (_log/X2_SCOPE_STATUS.md)
    { 53, 53,   1.637324,   1.237805,   0.796582,   0.102556 },   // I-I (n = 1, fit rms 0.62) X2I:pair i2_I-I class-A r2SCAN-3c, hand-inserted (_log/I2_CLF_STATUS.md)
    {  9, 17,   1.173822,   1.544609,   2.347998,   0.098277 },   // Cl-F (n = 1, fit rms 1.21)
    {  1, 17,   1.850313,   1.577804,   0.465050,   0.001089 },   // Cl-H (n = 1, fit rms 2.55)
    {  7, 17,   0.634339,   0.300000,   1.423038,  -0.036624 },   // Cl-N (n = 1, fit rms 1.22)
    {  8, 17,   0.870406,   1.523319,   1.727707,   0.127577 },   // Cl-O (n = 1, fit rms 1.26)
    {  9,  9,   0.550697,   1.962998,   3.696319,  -0.028962 },   // F-F (n = 1, fit rms 0.48)
    {  1,  9,   1.813339,   1.229057,   0.424163,  -0.150866 },   // F-H (n = 1, fit rms 0.88)
    {  7,  9,   0.690570,   0.958384,   0.774585,   0.060032 },   // F-N (n = 1, fit rms 1.24)
    {  8,  9,   0.446244,   1.318037,   3.391268,   0.060920 },   // F-O (n = 1, fit rms 1.46)
    {  1,  1,   1.412702,   1.114444,   0.135202,  -0.372385 },   // H-H (n = 1, fit rms 3.88)
    {  1,  7,   1.040014,   1.142257,   0.724591,   0.001348 },   // H-N (n = 1, fit rms 0.45)
    {  1,  8,   1.551760,   1.224739,   0.591084,  -0.138199 },   // H-O (n = 2, fit rms 3.03)
    {  7,  7,   0.643307,   1.186609,   1.797371,   0.090836 },   // N-N (n = 3, fit rms 1.86)
    {  7,  8,   0.637295,   1.315561,   0.613644,   0.130082 },   // N-O (n = 1, fit rms 0.97)
    {  8,  8,   0.880033,   1.064531,   1.176856,   0.106790 },   // O-O (n = 2, fit rms 7.45)
};

static constexpr std::size_t kPairCount = sizeof(kPairEntries) / sizeof(kPairEntries[0]);

static constexpr OrderEntry kOrderEntries[] = {
    {  1,  1, 1,   1.412702,   1.114444,   0.135202,  -0.372385 },   // H-H order 1 (n = 1, h2_H-H, fit rms 3.88)
    {  1,  6, 1,   1.031578,   1.063125,   0.426883,   0.000094 },   // C-H order 1 (n = 2, ch4_C-H+hcn_HC-H, fit rms 0.77)
    {  1,  7, 1,   1.040014,   1.142257,   0.724591,   0.001348 },   // H-N order 1 (n = 1, nh3_N-H, fit rms 0.45)
    {  1,  8, 1,   1.551760,   1.224739,   0.591084,  -0.138199 },   // H-O order 1 (n = 2, ch3oh_HO-H+h2o_O-H, fit rms 3.03)
    {  1,  9, 1,   1.813339,   1.229057,   0.424163,  -0.150866 },   // F-H order 1 (n = 1, hf_H-F, fit rms 0.88)
    {  1, 17, 1,   1.850313,   1.577804,   0.465050,   0.001089 },   // Cl-H order 1 (n = 1, hcl_H-Cl, fit rms 2.55)
    {  6,  6, 1,   1.174617,   1.258156,   0.343179,   0.051077 },   // C-C order 1 (n = 1, c2h6_C-C, fit rms 0.85)
    {  6,  6, 2,   1.001773,   1.184251,   0.305635,   0.046940 },   // C-C order 2 (n = 1, c2h4_CDC, fit rms 3.89)
    {  6,  6, 3,   0.920790,   1.024906,   0.786564,  -0.025162 },   // C-C order 3 (n = 1, c2h2_CTC, fit rms 7.84)
    {  6,  7, 1,   0.979462,   1.330789,   0.587651,   0.071653 },   // C-N order 1 (n = 1, ch3nh2_C-N, fit rms 0.40)
    {  6,  7, 2,   0.805185,   1.227120,   0.814170,   0.053747 },   // C-N order 2 (n = 1, ch2nh_CDN, fit rms 1.83)
    {  6,  7, 3,   0.815909,   1.052881,   0.974829,  -0.016531 },   // C-N order 3 (n = 1, hcn_CTN, fit rms 7.31)
    {  6,  8, 1,   1.095658,   1.300313,   0.446883,   0.049790 },   // C-O order 1 (n = 1, ch3oh_C-O, fit rms 2.47)
    {  6,  8, 2,   1.467046,   1.211688,   0.401442,   0.052762 },   // C-O order 2 (n = 1, h2co_CDO, fit rms 9.40)
    {  6,  8, 3,   1.561026,   0.998127,   0.297946,  -0.051941 },   // C-O order 3 (n = 1, co_CTO, fit rms 4.65)
    {  6,  9, 1,   1.306356,   1.076112,   0.501862,   0.096872 },   // C-F order 1 (n = 1, ch3f_C-F, fit rms 1.55)
    {  6, 17, 1,   1.545489,   1.320348,   0.383334,   0.110113 },   // C-Cl order 1 (n = 1, ch3cl_C-Cl, fit rms 0.80)
    {  7,  7, 1,   0.605735,   1.253018,   1.050705,   0.166018 },   // N-N order 1 (n = 1, n2h4_N-N, fit rms 0.82)
    {  7,  7, 2,   0.643307,   1.075029,   2.640398,   0.090836 },   // N-N order 2 (n = 1, n2h2_NDN, fit rms 1.86)
    {  7,  7, 3,   0.801500,   1.186609,   1.797371,  -0.001950 },   // N-N order 3 (n = 1, n2_NTN, fit rms 2.41)
    {  7,  8, 1,   0.637295,   1.315561,   0.613644,   0.130082 },   // N-O order 1 (n = 1, nh2oh_N-O, fit rms 0.97)
    {  7,  9, 1,   0.690570,   0.958384,   0.774585,   0.060032 },   // F-N order 1 (n = 1, nf3_N-F, fit rms 1.24)
    {  7, 17, 1,   0.634339,   0.300000,   1.423038,  -0.036624 },   // Cl-N order 1 (n = 1, ncl3_N-Cl, fit rms 1.22)
    {  8,  8, 1,   1.143136,   1.341020,   0.332648,   0.062740 },   // O-O order 1 (n = 1, h2o2_O-O, fit rms 13.01)
    {  8,  8, 3,   0.616930,   0.788043,   2.021064,   0.150840 },   // O-O order 3 (n = 1, o2_ODO, fit rms 1.89)
    {  8,  9, 1,   0.446244,   1.318037,   3.391268,   0.060920 },   // F-O order 1 (n = 1, of2_O-F, fit rms 1.46)
    {  8, 17, 1,   0.870406,   1.523319,   1.727707,   0.127577 },   // Cl-O order 1 (n = 1, hocl_O-Cl, fit rms 1.26)
    {  9,  9, 1,   0.550697,   1.962998,   3.696319,  -0.028962 },   // F-F order 1 (n = 1, f2_F-F, fit rms 0.48)
    {  9, 17, 1,   1.173822,   1.544609,   2.347998,   0.098277 },   // Cl-F order 1 (n = 1, clf_F-Cl, fit rms 1.21)
    { 17, 17, 1,   1.825132,   1.854651,   1.235720,   0.034200 },   // Cl-Cl order 1 (n = 1, cl2_Cl-Cl, fit rms 1.07)
    { 35, 35, 1,   1.183487,   1.224448,   1.021135,   0.067712 },   // Br-Br order 1 (n = 1, br2_Br-Br, fit rms 0.79) X2BR:order1 hand-inserted (_log/X2_SCOPE_STATUS.md)
    { 53, 53, 1,   1.637324,   1.237805,   0.796582,   0.102556 },   // I-I order 1 (n = 1, i2_I-I, fit rms 0.62) X2I:order1 hand-inserted (_log/I2_CLF_STATUS.md)
    // S-S order 3 (s2_SDS, s 0.704767 ca 0.718655 beta 0.753023 dr0 0.129960, fit rms 6.70) was hand-inserted
    // here by the PI_STAR campaign and REMOVED again (Sep 26, 2026, PI_STAR_STATUS.md section 12): with no
    // S-S order-1 row, findOrder clamps EVERY S-S bond onto it, so default rev-gfnff moved on 19 GMTKN55
    // structures (H2S2 +13, S8 +104 kcal/mol). The S2- pi-excess row no longer needs an order row.
};

static constexpr std::size_t kOrderCount = sizeof(kOrderEntries) / sizeof(kOrderEntries[0]);

// ================================================================================================
// HAND-MAINTAINED SECTION - NOT written by scripts/revgfnff_wellfit.py. If that script regenerates
// this file it must carry this block over verbatim (or the rows below have to be re-added).
//
// rev-gfnff P3 (Claude Generated, Sep 23, 2026; test_cases/revgfnff/_log/P2P3_STATUS.md): HALF-
// ORDER rows. A bond whose fragment carries an excess electron with no bonding slot left (Cl2-,
// F2-: the third electron sits in sigma*, a 2c-3e bond of order 1/2) has its continuous order
// lowered by x/2 (GFNFF::revExcessElectrons), and findOrder() below then interpolates between the
// order-1 row above and the order-0.5 row here. A pair that has NO row here is not eligible for
// the perception at all (hasHalfOrder()), so the mechanism is confined to where it was fitted.
//
// Source: DLPNO-CCSD(T)/aug-cc-pVTZ X2- curves (ref/E/{cl2m_Cl-Cl-,f2m_F-F-}_dlpno_ccsdt), NOT
// r2SCAN-3c (whose X2- curves carry a self-interaction tail, CL2F2_CCSDT_STATUS.md). Fitted on the
// full grid against the rest of the model evaluated with rev_sqe_phase1 + rev_excess_electron
// (localised charges), by the scratch fit recorded in P2P3_STATUS.md. `uncap` = 1: the inner side
// of this well is NOT capped at y = 2 (see FFWorkspace::calcBonds): the sigma* electron's extra
// wall has no other term to live in.
// ================================================================================================
struct HalfOrderEntry {
    int z1, z2;
    double s, ca, beta, dr0;
};

static constexpr HalfOrderEntry kHalfOrderEntries[] = {
    // fit of P2P3_STATUS.md section 3 (bonded points weight 1, reference tail beyond the static
    // bond cutoff weight 0.3), against the rest of the model with localised charges
    {  9,  9,   0.655464,   1.549085,   0.000000,   0.264120 },   // F-F  order 0.5 (F2-, D 45.2 kcal/mol, r_min 1.690 A)
    { 17, 17,   1.143785,   1.162928,   0.295217,   0.600037 },   // Cl-Cl order 0.5 (Cl2-, D 34.0 kcal/mol, r_min 2.568 A)
    {  9, 17,   2.419571,   1.816478,   0.781053,   0.398527 },   // Cl-F order 0.5 (ClF-, DLPNO-CCSD(T), D 110.3 kcal/mol, r_min 1.918 A, fit bonded rms 3.51 LOO 7.99) X2CLF:half
    { 35, 35,   1.200601,   1.136506,   0.395906,   0.531758 },   // Br-Br order 0.5 (Br2-, DLPNO-CCSD(T), D 55.2 kcal/mol, r_min 2.694 A, fit bonded rms 0.99 LOO 2.62) X2BR:half
    { 53, 53,   2.155195,   1.384566,   0.343513,   0.505417 },   // I-I order 0.5 (I2-, I2-, DLPNO-CCSD(T), D 66.7 kcal/mol, r_min 2.950 A, fit bonded rms 2.28 LOO 5.40) X2I:half
};

static constexpr std::size_t kHalfOrderCount = sizeof(kHalfOrderEntries) / sizeof(kHalfOrderEntries[0]);

/// true when the element pair has a half-order row, i.e. is eligible for the P3 perception
inline bool hasHalfOrder(int za, int zb)
{
    const int z1 = za < zb ? za : zb;
    const int z2 = za < zb ? zb : za;
    for (std::size_t k = 0; k < kHalfOrderCount; ++k)
        if (kHalfOrderEntries[k].z1 == z1 && kHalfOrderEntries[k].z2 == z2)
            return true;
    return false;
}

// ================================================================================================
// HAND-MAINTAINED SECTION (P3 pi* prototype, Claude Generated, Sep 25, 2026;
// test_cases/revgfnff/_log/PI_STAR_STATUS.md) - NOT written by scripts/revgfnff_wellfit.py.
//
// PI-EXCESS rows: the well of a DIATOMIC radical anion whose extra electron sits in pi* (O2-),
// perceived by GFNFF::revPiExcessElectrons (-gfnff.rev_pi_excess_electron). The bond's order
// row (findOrder at its unchanged continuous order) is blended towards this row with weight
// min(1, y). A pair without a row here is never perceived. Same (s, ca, beta, dr0) meaning as
// the rows above; capped like an ordinary well.
// ================================================================================================
struct PiExcessEntry {
    int z1, z2;
    double s, ca, beta, dr0;
};

static constexpr PiExcessEntry kPiExcessEntries[] = {
    // O-O: DLPNO-CCSD(T)/aug-cc-pVTZ O2- curve (ref/E/o2m_O-O-_dlpno_ccsdt, 12 naturally-bonded
    // points r=1.01-1.96 A out of 20; the model's own topology drops the bond past 1.96 A;
    // no react-mode/kept-topology tail extension attempted, see PI_STAR_STATUS.md), fragment-
    // referenced against O (triplet) + O- (doublet). REFIT Sep 26, 2026 (PI_STAR_STATUS.md section
    // 12): the first fit reconstructed the well with CURCUMA_BONDDUMP's r0_dyn, which lacks the
    // stage-3a(i) pair-CN correction the kernel applies (runtime r0 ~ constant 1.81 Bohr, r0_dyn
    // falls to 1.24 at 1.96 A) - that row gave 19.2 kcal/mol at runtime, not its reported 3.04.
    // This row is fitted against the RUNTIME r0/fc/alpha (CURCUMA_WELLDUMP): rms 2.83 at runtime.
    {  8,  8,   0.798346,   1.188780,   1.507767,   0.375625 },   // O-O (n = 12, o2m_O-O-, fit rms 2.83, runtime r0) PISTAR:pi-excess refit section 12
    // S-S: DLPNO-CCSD(T)/aug-cc-pVTZ S2- curve (ref/E/s2m_S-S-_dlpno_ccsdt, 11 naturally-bonded
    // points r=1.60-2.60 A out of 20; the model's own topology drops the bond past 2.60 A; no
    // react-mode/kept-topology tail extension attempted, see PI_STAR_STATUS.md), fragment-
    // referenced against S (triplet) + S- (doublet), fit rms 0.26 kcal/mol.
    { 16, 16,   0.582195,   0.765328,   0.175854,   0.286630 },   // S-S (n = 11, s2m_S-S-, fit rms 0.26, runtime r0) PISTAR:pi-excess refit section 12
};

static constexpr std::size_t kPiExcessCount = sizeof(kPiExcessEntries) / sizeof(kPiExcessEntries[0]);

/// true when the element pair has a pi-excess row, i.e. is eligible for the pi* perception
inline bool hasPiExcess(int za, int zb)
{
    const int z1 = za < zb ? za : zb;
    const int z2 = za < zb ? zb : za;
    for (std::size_t k = 0; k < kPiExcessCount; ++k)
        if (kPiExcessEntries[k].z1 == z1 && kPiExcessEntries[k].z2 == z2)
            return true;
    return false;
}

/// blend (s, ca, beta, dr0) towards the pair's pi-excess row with weight min(1, y); no-op for a
/// pair without a row or y <= 0
inline void applyPiExcess(int za, int zb, double y, double& s, double& ca, double& beta, double& dr0)
{
    if (!(y > 0.0))
        return;
    const int z1 = za < zb ? za : zb;
    const int z2 = za < zb ? zb : za;
    const double t = y < 1.0 ? y : 1.0;
    for (std::size_t k = 0; k < kPiExcessCount; ++k) {
        const PiExcessEntry& pe = kPiExcessEntries[k];
        if (pe.z1 != z1 || pe.z2 != z2)
            continue;
        s += t * (pe.s - s);
        ca += t * (pe.ca - ca);
        beta += t * (pe.beta - beta);
        dr0 += t * (pe.dr0 - dr0);
        return;
    }
}

/// rev-gfnff P3: the half-order blend weight t in [0, 1] of a pair at a continuous order
/// (0 at order >= 1 or for a pair without a half row, 1 at order <= 0.5). The well kernel
/// uses it to switch the inner-side cap off in proportion (see FFWorkspace::calcBonds).
inline double halfOrderWeight(int za, int zb, double order)
{
    if (!(order < 1.0) || !hasHalfOrder(za, zb))
        return 0.0;
    return std::min(1.0, std::max(0.0, (1.0 - order) / 0.5));
}

/// The element-pair entry, or nullptr when the class-A set has no data for that pair - the
/// caller then falls back to the delivered Gaussian and says so at verbosity 2.
inline const Entry* find(int za, int zb)
{
    const int z1 = za < zb ? za : zb;
    const int z2 = za < zb ? zb : za;
    for (std::size_t k = 0; k < kPairCount; ++k)
        if (kPairEntries[k].z1 == z1 && kPairEntries[k].z2 == z2)
            return &kPairEntries[k];
    return nullptr;
}

/// The bond-order-resolved parameters of an element pair at a CONTINUOUS order, linearly
/// interpolated between the nominal orders the class-A set covers for that pair and CLAMPED at
/// the lowest / highest of them.  Returns false when the pair has no order row at all (the
/// caller then uses find() above, i.e. the element-pair fit).
///
/// The interpolation is Lipschitz in \p order and \p order is a topology constant inside one
/// energy call, so this introduces no geometry derivative and no switch: a pair whose pi order
/// drifts moves its well parameters proportionally, never in a step.  A pair the class-A set
/// covers at ONE order only (e.g. C-H, which has no double or triple member) returns that row
/// for every order, i.e. it behaves exactly like the element-pair table.
inline bool findOrder(int za, int zb, double order, double& s, double& ca, double& beta, double& dr0)
{
    const int z1 = za < zb ? za : zb;
    const int z2 = za < zb ? zb : za;
    // rev-gfnff P3 (Sep 23, 2026): below order 1, interpolate towards the half-order row of the
    // pair if it has one. An order >= 1 never reaches this branch, so every existing result is
    // bit-identical; a pair without a half row falls through to the clamp below (order-1 row).
    if (order < 1.0) {
        for (std::size_t h = 0; h < kHalfOrderCount; ++h) {
            const HalfOrderEntry& he = kHalfOrderEntries[h];
            if (he.z1 != z1 || he.z2 != z2)
                continue;
            const OrderEntry* one = nullptr;
            for (std::size_t k = 0; k < kOrderCount; ++k)
                if (kOrderEntries[k].z1 == z1 && kOrderEntries[k].z2 == z2 && kOrderEntries[k].order == 1)
                    one = &kOrderEntries[k];
            if (!one)
                break;
            const double t = std::min(1.0, std::max(0.0, (1.0 - order) / 0.5)); // 0 at order 1, 1 at 0.5
            s = one->s + t * (he.s - one->s);
            ca = one->ca + t * (he.ca - one->ca);
            beta = one->beta + t * (he.beta - one->beta);
            dr0 = one->dr0 + t * (he.dr0 - one->dr0);
            return true;
        }
    }
    const OrderEntry* lo = nullptr;
    const OrderEntry* hi = nullptr;
    for (std::size_t k = 0; k < kOrderCount; ++k) {
        const OrderEntry& e = kOrderEntries[k];
        if (e.z1 != z1 || e.z2 != z2)
            continue;
        const double o = static_cast<double>(e.order);
        if (o <= order && (!lo || o > static_cast<double>(lo->order)))
            lo = &e;
        if (o >= order && (!hi || o < static_cast<double>(hi->order)))
            hi = &e;
    }
    if (!lo && !hi)
        return false;
    if (!lo)
        lo = hi;                       // order below the lowest fitted one -> clamp
    if (!hi)
        hi = lo;                       // order above the highest fitted one -> clamp
    double t = 0.0;
    if (hi->order != lo->order)
        t = (order - static_cast<double>(lo->order))
            / static_cast<double>(hi->order - lo->order);
    s = lo->s + t * (hi->s - lo->s);
    ca = lo->ca + t * (hi->ca - lo->ca);
    beta = lo->beta + t * (hi->beta - lo->beta);
    dr0 = lo->dr0 + t * (hi->dr0 - lo->dr0);
    return true;
}

} // namespace RevWellTableV2
