/*
 * <Citation Registry Implementation>
 * Copyright (C) 2019 - 2025 Conrad Hübler <Conrad.Huebler@gmx.net>
 */

#include "citation_registry.h"
#include "citation_database.h"
#include "curcuma_logger.h"

#include <fmt/color.h>
#include <fmt/core.h>
#include <fstream>
#include <set>

// Static member definitions
std::vector<std::string> CitationRegistry::m_cited_keys;
std::set<std::string> CitationRegistry::m_seen;
std::vector<std::pair<std::string, std::string>> CitationRegistry::m_subrefs;

void CitationRegistry::cite(const std::string& key, const std::string& parent)
{
    // Already cited — silent no-op
    if (m_seen.count(key)) return;

    // Look up citation data
    const Citations::CitationData* data = Citations::lookup(key);
    if (!data) {
        CurcumaLogger::warn("CitationRegistry: unknown key '" + key + "'");
        return;
    }

    // Register
    m_cited_keys.push_back(key);
    m_seen.insert(key);

    // Track sub-reference relationship
    if (!parent.empty()) {
        m_subrefs.push_back({key, parent});
    }

    // Log — always visible, regardless of verbosity
    CurcumaLogger::info("[CITE]  " + key + ": " + data->description);
}

void CitationRegistry::printSummary()
{
    if (m_cited_keys.empty()) return;

    fmt::print("\n");
    fmt::print(fg(fmt::color::green), "===============================================================\n");
    fmt::print(fg(fmt::color::green), "  Please cite the following references for methods used in this run:\n");
    fmt::print(fg(fmt::color::green), "===============================================================\n");

    // Collect sub-ref children per parent
    std::set<std::string> children;
    for (const auto& [child, parent] : m_subrefs) {
        children.insert(child);
    }

    // Helper: print one entry (description + reference, two lines)
    auto printEntry = [](const std::string& prefix, const Citations::CitationData* data) {
        fmt::print(fg(fmt::color::green), "  [CITE]  {}\n", prefix + data->description);
        fmt::print(fg(fmt::color::green), "          {}\n", data->reference);
    };

    // Print top-level entries (those that are not children of another)
    for (const auto& key : m_cited_keys) {
        if (children.count(key)) continue;

        const Citations::CitationData* data = Citations::lookup(key);
        if (!data) continue;

        printEntry("", data);

        // Print sub-references of this parent (indented, without raw key)
        for (const auto& [child, parent] : m_subrefs) {
            if (parent != key) continue;
            const Citations::CitationData* child_data = Citations::lookup(child);
            if (!child_data) continue;
            printEntry("  -> ", child_data);
        }
    }

    fmt::print(fg(fmt::color::green), "===============================================================\n");
}

void CitationRegistry::writeBibTeX(const std::string& output_dir, const std::string& basename)
{
    if (m_cited_keys.empty()) return;

    // Derive filename
    std::string filename;
    if (!basename.empty()) {
        std::string stem = basename;
        auto dot = stem.rfind('.');
        if (dot != std::string::npos) stem = stem.substr(0, dot);
        filename = stem + "_citations.bib";
    } else {
        filename = "curcuma_citations.bib";
    }

    if (!output_dir.empty()) {
        filename = output_dir + "/" + filename;
    }

    std::ofstream ofs(filename);
    if (!ofs.is_open()) {
        CurcumaLogger::warn("CitationRegistry: cannot write BibTeX to '" + filename + "'");
        return;
    }

    ofs << "% Citations generated by Curcuma\n\n";

    for (const auto& key : m_cited_keys) {
        const Citations::CitationData* data = Citations::lookup(key);
        if (!data || data->bibtex.empty()) continue;
        ofs << data->bibtex << "\n\n";
    }

    ofs.close();
    CurcumaLogger::info("BibTeX written to: " + filename);
}

void CitationRegistry::clear()
{
    m_cited_keys.clear();
    m_seen.clear();
    m_subrefs.clear();
}

bool CitationRegistry::hasKey(const std::string& key)
{
    return m_seen.count(key) > 0;
}