#!/usr/bin/env python3
# Claude Generated (June 2026): extract the CM5 charge-model tables from tblite.
#
# Sources:
#   external/tblite/src/tblite/solvation/cm5.f90      (cm5_a0(118), cm5_alpha, pair overrides)
#   external/tblite/src/tblite/data/atomicrad.f90     (atomic_rad(118), in Angstrom * aatoau)
# Emits:
#   src/core/solvation/cm5_data.h
#
# CM5 charges are needed only for the GFN1-xTB ALPB/GBSA solvation path
# (q_solute = q_Mulliken + cm5). See docs/SQM_SOLVATION_WP.md WP0.3 / WP1.1.

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CM5_F90 = os.path.join(ROOT, "external", "tblite", "src", "tblite", "solvation", "cm5.f90")
RAD_F90 = os.path.join(ROOT, "external", "tblite", "src", "tblite", "data", "atomicrad.f90")
OUT = os.path.join(ROOT, "src", "core", "solvation", "cm5_data.h")

NUM_RE = re.compile(r"[-+]?\d*\.\d+(?:[dDeE][-+]?\d+)?_wp|[-+]?\d+\.(?:[dDeE][-+]?\d+)?_wp")
NELEM = 118


def parse_numbers(body):
    out = []
    for m in NUM_RE.finditer(body):
        tok = m.group(0).replace("_wp", "").replace("d", "e").replace("D", "e")
        out.append(float(tok))
    return out


def extract_array(path, anchor):
    """Return the float list inside the array literal that follows `anchor`."""
    with open(path) as f:
        text = f.read()
    i = text.find(anchor)
    if i < 0:
        sys.exit(f"ERROR: '{anchor}' not found in {path}")
    # Take from the '(/' or '[' after the anchor up to the closing '/)' or ']'.
    seg = text[i:]
    start = re.search(r"\(/|\[", seg)
    end = re.search(r"/\)|\]", seg[start.end():])
    body = seg[start.end():start.end() + end.start()]
    nums = parse_numbers(body)
    if len(nums) != NELEM:
        sys.exit(f"ERROR: {anchor} -> {len(nums)} numbers (expected {NELEM})")
    return nums


def fmt_rows(vals):
    rows = []
    for r in range(0, len(vals), 6):
        chunk = vals[r:r + 6]
        rows.append("    " + ", ".join(f"{v: .4f}" for v in chunk) + ",")
    return "\n".join(rows)


def main():
    a0 = extract_array(CM5_F90, "cm5_a0(max_elements)")
    rad_aa = extract_array(RAD_F90, "atomic_rad(max_elem)")  # in Angstrom (pre aatoau scale)

    with open(OUT, "w") as f:
        f.write(HEADER)
        f.write("inline const double cm5_a0[118] = {\n")
        f.write(fmt_rows(a0))
        f.write("\n};\n\n")
        f.write("// Atomic radii (Angstrom) from tblite data/atomicrad.f90; multiply by\n")
        f.write("// CurcumaUnit::AA_TO_AU for Bohr.\n")
        f.write("inline const double cm5_atomic_rad_aa[118] = {\n")
        f.write(fmt_rows(rad_aa))
        f.write("\n};\n\n")
        f.write(FOOTER)

    print(f"Wrote {OUT}")
    print(f"  cm5_a0[0]={a0[0]} (H), cm5_a0[5]={a0[5]} (C), cm5_a0[6]={a0[6]} (N), cm5_a0[7]={a0[7]} (O)")
    print(f"  rad_aa[0]={rad_aa[0]} (H), rad_aa[5]={rad_aa[5]} (C)")


HEADER = """/*
 * <CM5 charge-model tables (tblite)>
 * Copyright (C) 2019 - 2026 Conrad Hübler <Conrad.Huebler@gmx.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * AUTO-GENERATED by scripts/extract_tblite_cm5.py — DO NOT EDIT.
 * Source: tblite cm5.f90 + data/atomicrad.f90.
 *
 * CM5 (Charge Model 5) atomic parameters and atomic radii, used by the native
 * GFN1-xTB ALPB/GBSA solvation path: the Born matrix and CDS H-bond are
 * contracted with q_solute = q_Mulliken + cm5(geometry). The cm5 correction is
 * geometry-only (independent of the SCF charges).
 * Reference: Marenich, Cramer, Truhlar, J. Chem. Theory Comput. 2012, 8, 527.
 */

#pragma once

namespace curcuma {
namespace solvation {

// CM5 width parameter (1/Angstrom in the paper). Divide by AA_TO_AU (Bohr/Angstrom)
// at use to obtain 1/Bohr, matching tblite: cm5_alpha = 2.4740_wp / aatoau.
inline constexpr double cm5_alpha_per_aa = 2.4740;

"""

FOOTER = """// Element-pair parameter overrides (Fortran 1-based Z): pairpar(Zi,Zj).
// pairpar(Zi,Zj) defaults to cm5_a0[Zi-1]-cm5_a0[Zj-1]; these pairs override it,
// and pairpar(Zj,Zi) = -pairpar(Zi,Zj). (cm5.f90:89-94)
struct Cm5PairOverride { int zi; int zj; double pij; };
inline const Cm5PairOverride cm5_pair_overrides[6] = {
    {1, 6,  0.0502},
    {1, 7,  0.1747},
    {1, 8,  0.1671},
    {6, 7,  0.0556},
    {6, 8,  0.0234},
    {7, 8, -0.0346},
};

} // namespace solvation
} // namespace curcuma
"""


if __name__ == "__main__":
    main()
