#!/usr/bin/env python3
"""rev-gfnff react-MD smoothness tail sweep with paired replicates (package 11).

Claude Generated (Sep 2026).  Copyright (C) 2019 - 2026 Conrad Huebler.

WHY THIS EXISTS
---------------
A react-mode MD "tail" number (the largest per-step |dEpot| a trajectory produces) is a
RARE-EVENT statistic of a CHAOTIC trajectory: a 1-ulp change in the potential is amplified
by the dynamics, and ``-md.seed`` does NOT vary the initial velocities on this path, so one
run per (cell, arm) is ONE sample and cannot be told apart from luck.  Package 10's 130-cell
aggregate and the orchestrator's single-cell spot-check disagreed for exactly that reason.

This harness therefore

  * runs K REPLICATES per cell, generated by a tiny (~1e-5 A) random displacement of every
    atom of the start geometry.  Replicate 0 is the UNPERTURBED geometry, so the historical
    single-run numbers are contained in the output as ``replicate == 0``;
  * uses the SAME replicate geometries for every arm and every time step, so every
    comparison against the ``mg`` reference arm is PAIRED on (cell, replicate);
  * writes one CSV row per (cell, replicate, arm, dt) -- the raw data, not an aggregate;
  * never stores a raw MD log: stdout is parsed while it streams and the run directory is
    deleted immediately afterwards (a verbosity-1 log of a 5 ps / 0.0625 fs run is ~19 MB,
    and the full sweep is >10000 runs).

PRE-REGISTERED DECISION STATISTIC (fixed before the sweep was run; see
``test_cases/revgfnff/_log/WORK_STATUS.md`` package 11)
-------------------------------------------------------------------------------------------
Per trajectory: ``max_step_kj`` = max over steps of |Epot(i+1) - Epot(i)| in kJ/mol, with
every interval whose end row is preceded by a ``REACT rebuild`` line excluded (identical to
the parser packages 7/9/10 used).  A trajectory is BAD iff ``max_step_kj >= 100``.

Primary statistic, per (arm, dt): ``p = #bad / #trajectories`` over all cells x replicates.
Decision rule: arm X is WORSE than ``mg`` at a given dt iff the paired difference
``dp = p_X - p_mg`` is positive AND its 95 % cluster-bootstrap CI (resample the 130 CELLS
with replacement, keeping all replicates of a drawn cell and the pairing, 10000 draws)
excludes 0.  Otherwise the two arms are "not distinguishable at K replicates".
Reported alongside, descriptive only (it ignores the clustering): the exact McNemar
binomial p-value on the discordant (cell, replicate) pairs.

Secondary, pre-registered: the distribution of ``max_step_kj`` per arm (median / p90 / p99 /
max), the same bad-fraction at a 50 kJ/mol threshold, events >= 50 kJ/mol per ps, the rebuild
``dE_jump`` tail, T_max, and the OVERLAP of the failing-cell sets between arms.

USAGE
-----
  # 1. reproduce the anchor (c2h6/T2000_f0, true dt 0.25, unperturbed) -- must match
  #    mg 28 rebuilds / 28.3 kJ / 0 events / 5206 K before anything else counts
  revgfnff_tail_sweep.py anchor --binary /path/to/curcuma

  # 2. the sweep (writes/extends the CSV; --jobs 8 single-thread processes)
  revgfnff_tail_sweep.py sweep --binary /path/to/curcuma \
      --out test_cases/revgfnff/_log/tail_remeasure.csv \
      --arms mg,mg2,mg3,gauss,gauss_delivered --dts 0.25,0.125,0.0625 \
      --replicates 5 --maxtime 5000 --jobs 8

  # 3. the pre-registered analysis
  revgfnff_tail_sweep.py analyze --csv test_cases/revgfnff/_log/tail_remeasure.csv

  # 4. one run with its log kept (for a per-term attribution)
  revgfnff_tail_sweep.py one --binary ... --cell c2h6_T2000_f0 --arm mg3 --dt 0.25 \
      --replicate 0 --keep /some/dir
"""

import argparse
import csv
import math
import os
import random
import re
import shutil
import subprocess
import sys
import tempfile
import time
import zlib
from concurrent.futures import ProcessPoolExecutor

HARTREE_TO_KJ = 2625.4996394799

ANSI = re.compile(r"\x1b\[[0-9;]*m")
# Same status-row matcher as the package-7/9/10 parsers: >= 14 consecutive plain floats.
STATUS = re.compile(r"^\s*(-?\d+\.\d+)(\s+-?\d+\.\d+){13,}")
REBUILD = re.compile(r"REACT rebuild #(\d+)")
JUMP = re.compile(r"dE_jump\s*=\s*(-?\d+\.\d+)\s*Eh")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FITWORK = os.path.join(REPO, "test_cases", "revgfnff", "fit_work")

# The 130-cell set of packages 7 and 10: three systems, every frame of each, two temperatures.
SYSTEMS = [("c2h6", "c2h6_1000K.xyz", 25),
           ("ch3nh2", "ch3nh2_1000K.xyz", 25),
           ("ch4_H", "ch4_H.xyz", 15)]
TEMPERATURES = [1000, 2000]

# Arms. Everything not listed here stays at the shipped default (rev_share_form conserving,
# rev_share_donor_rule true, rev_budget_fix_h true) -- confirmed via CURCUMA_REVDUMP=1.
ARMS = {
    "mg":              ["-gfnff.rev_well_form", "mg"],
    "mg2":             ["-gfnff.rev_well_form", "mg2"],
    "mg3":             ["-gfnff.rev_well_form", "mg3"],
    "gauss":           ["-gfnff.rev_well_form", "gauss"],
    "gauss_delivered": ["-gfnff.rev_well_form", "gauss",
                        "-gfnff.rev_share_form", "delivered"],
}
REFERENCE_ARM = "mg"

PERTURB_AMPLITUDE_A = 1.0e-5      # |displacement| per atom, exactly, in Angstrom
BAD_THRESHOLD_KJ = 100.0          # primary
SECOND_THRESHOLD_KJ = 50.0        # secondary

CSV_FIELDS = ["cell", "system", "temperature", "frame", "replicate", "perturb_seed",
              "perturb_amp_A", "arm", "dt_fs", "maxtime_fs", "max_step_kj", "n_ge50",
              "n_ge100", "rebuilds", "t_max_k", "max_jump_kj", "n_jump_ge50", "rows",
              "duration_ps", "rc", "wall_s"]


# --------------------------------------------------------------------------- cells / geometry

def cell_list():
    out = []
    for name, fname, nframes in SYSTEMS:
        for T in TEMPERATURES:
            for f in range(nframes):
                out.append({"cell": "%s_T%d_f%d" % (name, T, f), "system": name,
                            "file": os.path.join(FITWORK, fname), "frame": f, "temperature": T})
    return out


def read_frame(path, index):
    """Return (natoms, comment, [(sym, x, y, z), ...]) for one frame of a multi-frame XYZ."""
    lines = open(path).read().splitlines()
    frames, i = [], 0
    while i < len(lines):
        if not lines[i].strip():
            i += 1
            continue
        na = int(lines[i].split()[0])
        frames.append(lines[i:i + na + 2])
        i += na + 2
    if index >= len(frames):
        raise SystemExit("frame %d >= %d in %s" % (index, len(frames), path))
    blk = frames[index]
    na = int(blk[0].split()[0])
    atoms = []
    for ln in blk[2:2 + na]:
        f = ln.split()
        atoms.append((f[0], float(f[1]), float(f[2]), float(f[3])))
    return na, blk[1], atoms


def perturb_seed(cell, replicate):
    """Deterministic and independent of the arm and the time step -- that is what makes the
    comparison paired.  crc32 instead of hash(): Python randomises str hashes per process."""
    return (zlib.crc32(cell.encode()) & 0x7fffffff) * 1000 + replicate


def perturbed_atoms(atoms, seed, replicate, amp=PERTURB_AMPLITUDE_A):
    """Replicate 0 is the untouched geometry.  Otherwise every atom is displaced by a vector
    of EXACTLY `amp` Angstrom in a uniformly random direction."""
    if replicate == 0:
        return atoms
    rng = random.Random(seed)
    out = []
    for (s, x, y, z) in atoms:
        while True:
            v = [rng.gauss(0.0, 1.0) for _ in range(3)]
            n = math.sqrt(sum(c * c for c in v))
            if n > 1e-12:
                break
        v = [c * amp / n for c in v]
        out.append((s, x + v[0], y + v[1], z + v[2]))
    return out


def write_xyz(path, comment, atoms):
    with open(path, "w") as fh:
        fh.write("%d\n%s\n" % (len(atoms), comment))
        for (s, x, y, z) in atoms:
            fh.write("%-3s %20.14f %20.14f %20.14f\n" % (s, x, y, z))


# --------------------------------------------------------------------------- run + stream parse

def md_argv(binary, temperature, dt, maxtime, arm_flags):
    """The protocol of packages 7/10 (run_one.sh / rundt.sh), at verbosity 1 so the status rows
    and the REACT lines are both present while the log stays ~250 bytes per step.
    rev_dt_cap (0.25) is left at its default: it only clamps requests ABOVE it."""
    return [binary, "-md", "input.xyz", "-method", "revgfnff",
            "-gfnff.topology_mode", "react", "-temperature", str(temperature),
            "-maxtime", str(maxtime), "-md.time_step", str(dt),
            "-md.thermostat", "csvr", "-md.coupling", "10",
            "-md.rattle_12", "false", "-md.no_restart", "-md.seed", "42",
            "-threads", "1", "-verbosity", "1", "-md.print_frequency", "1",
            "-no_bmt"] + list(arm_flags)


def parse_stream(lines):
    """Streaming version of the package-7/9/10 parser.  Consumes an iterable of raw stdout
    lines and returns the per-trajectory statistics; nothing is retained."""
    prev = None
    pending_rebuild = False
    max_step = 0.0
    n50 = n100 = 0
    rebuilds = 0
    tmax = float("-inf")
    rows = 0
    max_jump = 0.0
    n_jump50 = 0
    last_time = 0.0
    for raw in lines:
        l = raw.rstrip("\n")
        if "\x1b" in l:
            l = ANSI.sub("", l)
        if not l:
            continue
        head = l[0]
        if head == " " or head == "-" or head.isdigit():
            # fast path: candidate status row, cannot contain "REACT rebuild"
            if not STATUS.match(l):
                continue
            f = l.split()
            try:
                t_ps, epot, temp = float(f[0]), float(f[1]), float(f[7])
            except (IndexError, ValueError):
                continue
            rows += 1
            last_time = t_ps
            if temp == temp:
                tmax = max(tmax, temp)
            if prev is not None and not pending_rebuild and epot == epot and prev == prev:
                d = abs(epot - prev) * HARTREE_TO_KJ
                if d > max_step:
                    max_step = d
                n50 += d >= SECOND_THRESHOLD_KJ
                n100 += d >= BAD_THRESHOLD_KJ
            prev = epot
            pending_rebuild = False
            continue
        m = REBUILD.search(l)
        if m:
            rebuilds = max(rebuilds, int(m.group(1)))
            pending_rebuild = True
            j = JUMP.search(l)
            if j:
                v = abs(float(j.group(1))) * HARTREE_TO_KJ
                max_jump = max(max_jump, v)
                n_jump50 += v >= SECOND_THRESHOLD_KJ
    return {"max_step_kj": max_step, "n_ge50": n50, "n_ge100": n100, "rebuilds": rebuilds,
            "t_max_k": (tmax if tmax > float("-inf") else float("nan")), "rows": rows,
            "max_jump_kj": max_jump, "n_jump_ge50": n_jump50, "duration_ps": last_time}


def run_one(binary, cell, replicate, arm, dt, maxtime, keep=None, scratch=None):
    na, comment, atoms = read_frame(cell["file"], cell["frame"])
    seed = perturb_seed(cell["cell"], replicate)
    atoms = perturbed_atoms(atoms, seed, replicate)
    workdir = keep if keep else tempfile.mkdtemp(prefix="p11_", dir=scratch)
    if keep:
        os.makedirs(workdir, exist_ok=True)
    try:
        # A stale .topo.json next to the basename would silently supply another molecule's
        # perceived topology (Known Issue #11/#28): a fresh directory per run, always.
        for f in os.listdir(workdir):
            if f.endswith(".topo.json"):
                os.remove(os.path.join(workdir, f))
        write_xyz(os.path.join(workdir, "input.xyz"), comment, atoms)
        argv = md_argv(binary, cell["temperature"], dt, maxtime, ARMS[arm])
        with open(os.path.join(workdir, "cmd.txt"), "w") as fh:
            fh.write(" ".join(argv) + "\n")
        t0 = time.time()
        proc = subprocess.Popen(argv, cwd=workdir, stdout=subprocess.PIPE,
                                stderr=subprocess.STDOUT, text=True, errors="replace",
                                bufsize=1 << 20)
        if keep:
            log = open(os.path.join(workdir, "run.log"), "w")

            def gen():
                for line in proc.stdout:
                    log.write(line)
                    yield line
            stat = parse_stream(gen())
            log.close()
        else:
            stat = parse_stream(proc.stdout)
        proc.stdout.close()
        rc = proc.wait()
        wall = time.time() - t0
    finally:
        if not keep:
            shutil.rmtree(workdir, ignore_errors=True)
    stat.update({"cell": cell["cell"], "system": cell["system"],
                 "temperature": cell["temperature"], "frame": cell["frame"],
                 "replicate": replicate, "perturb_seed": seed if replicate else 0,
                 "perturb_amp_A": PERTURB_AMPLITUDE_A if replicate else 0.0,
                 "arm": arm, "dt_fs": dt, "maxtime_fs": maxtime, "rc": rc,
                 "wall_s": round(wall, 2)})
    return stat


def fmt_row(s):
    return {k: (("%.4g" % s[k]) if isinstance(s[k], float) and k not in
                ("dt_fs", "perturb_amp_A", "wall_s") else s[k]) for k in CSV_FIELDS}


# --------------------------------------------------------------------------- sweep driver

def cmd_sweep(a):
    cells = cell_list()
    if a.cells:
        want = set(a.cells.split(","))
        cells = [c for c in cells if c["cell"] in want]
    arms = a.arms.split(",")
    dts = [float(x) for x in a.dts.split(",")]
    reps = list(range(0, a.replicates + 1))          # replicate 0 = unperturbed
    jobs = [(c, r, arm, dt) for c in cells for r in reps for arm in arms for dt in dts]
    done = set()
    exists = os.path.isfile(a.out)
    if exists and not a.overwrite:
        with open(a.out) as fh:
            for row in csv.DictReader(fh):
                done.add((row["cell"], int(row["replicate"]), row["arm"], float(row["dt_fs"])))
    jobs = [j for j in jobs if (j[0]["cell"], j[1], j[2], j[3]) not in done]
    print("cells %d  arms %s  dts %s  replicates %s  -> %d runs pending"
          % (len(cells), arms, dts, reps, len(jobs)), flush=True)
    if not jobs:
        return
    scratch = a.scratch or tempfile.gettempdir()
    mode = "w" if (a.overwrite or not exists) else "a"
    fh = open(a.out, mode, newline="")
    w = csv.DictWriter(fh, fieldnames=CSV_FIELDS)
    if mode == "w":
        w.writeheader()
    n = 0
    t0 = time.time()
    with ProcessPoolExecutor(max_workers=a.jobs) as ex:   # processes: the parse is GIL-bound
        futs = [ex.submit(run_one, a.binary, c, r, arm, dt, a.maxtime, None, scratch)
                for (c, r, arm, dt) in jobs]
        for fu in futs:
            w.writerow(fmt_row(fu.result()))
            n += 1
            if n % 200 == 0:
                fh.flush()
                el = time.time() - t0
                print("  %d/%d  %.0f s elapsed, ~%.0f s left"
                      % (n, len(jobs), el, el / n * (len(jobs) - n)), flush=True)
    fh.close()
    print("wrote %d rows -> %s (%.0f s)" % (n, a.out, time.time() - t0))


def cmd_one(a):
    cells = {c["cell"]: c for c in cell_list()}
    s = run_one(a.binary, cells[a.cell], a.replicate, a.arm, a.dt, a.maxtime, keep=a.keep)
    print(" ".join("%s=%s" % (k, s[k]) for k in
                   ("cell", "replicate", "arm", "dt_fs", "rebuilds", "max_step_kj",
                    "n_ge50", "n_ge100", "t_max_k", "rows", "rc")))


def cmd_anchor(a):
    """The orchestrator's spot check: c2h6/T2000_f0, true dt 0.25, unperturbed, 5 ps.
    mg 28 / 28.3 / 0 / 5206 -- mg2 26 / 32.2 / 0 / 5069 -- mg3 42 / 256.8 / 12 / 7030."""
    expect = {"mg": (28, 28.3, 0, 5206), "mg2": (26, 32.2, 0, 5069), "mg3": (42, 256.8, 12, 7030)}
    cells = {c["cell"]: c for c in cell_list()}
    ok = True
    for arm in ("mg", "mg2", "mg3"):
        s = run_one(a.binary, cells["c2h6_T2000_f0"], 0, arm, 0.25, 5000)
        got = (s["rebuilds"], round(s["max_step_kj"], 1), s["n_ge50"], round(s["t_max_k"]))
        good = got == expect[arm]
        ok &= good
        print("%-4s rebuilds %3d  max %7.1f kJ  n>=50 %3d  T_max %6.0f K   %s (expect %s)"
              % (arm, got[0], got[1], got[2], got[3], "OK" if good else "MISMATCH", expect[arm]))
    print("ANCHOR", "REPRODUCED" if ok else "FAILED")
    return 0 if ok else 1


# --------------------------------------------------------------------------- analysis

def load(csvpath):
    rows = []
    with open(csvpath) as fh:
        for r in csv.DictReader(fh):
            r["replicate"] = int(r["replicate"])
            r["dt_fs"] = float(r["dt_fs"])
            for k in ("max_step_kj", "t_max_k", "max_jump_kj", "duration_ps"):
                r[k] = float(r[k])
            for k in ("n_ge50", "n_ge100", "rebuilds", "n_jump_ge50", "rows", "rc"):
                r[k] = int(float(r[k]))
            rows.append(r)
    return rows


def quantile(v, f):
    if not v:
        return float("nan")
    v = sorted(v)
    k = (len(v) - 1) * f
    lo, hi = int(math.floor(k)), int(math.ceil(k))
    return v[lo] if lo == hi else v[lo] + (v[hi] - v[lo]) * (k - lo)


def binom_two_sided(b, c):
    """Exact McNemar: P(|X - n/2| >= |b - n/2|) for X ~ Bin(n = b + c, 1/2)."""
    n = b + c
    if n == 0:
        return 1.0
    obs = math.comb(n, b)
    tot = sum(math.comb(n, k) for k in range(n + 1))
    p = sum(math.comb(n, k) for k in range(n + 1) if math.comb(n, k) <= obs) / tot
    return min(1.0, p)


def cluster_bootstrap(by_cell, arm, ref, draws, rng, threshold):
    """Resample CELLS with replacement (all replicates of a drawn cell, pairing kept)."""
    cells = list(by_cell.keys())
    ps, pr, dd = [], [], []
    for _ in range(draws):
        pick = [cells[rng.randrange(len(cells))] for _ in cells]
        na = ba = nr = br = 0
        for c in pick:
            for rep, d in by_cell[c].items():
                if arm in d:
                    na += 1
                    ba += d[arm] >= threshold
                if ref in d:
                    nr += 1
                    br += d[ref] >= threshold
        if na and nr:
            ps.append(ba / na)
            pr.append(br / nr)
            dd.append(ba / na - br / nr)
    return ps, dd


def cmd_analyze(a):
    rows = load(a.csv)
    dts = sorted({r["dt_fs"] for r in rows}, reverse=True)
    arms = sorted({r["arm"] for r in rows},
                  key=lambda x: (x != REFERENCE_ARM, x))
    rng = random.Random(20260921)
    print("rows %d   cells %d   replicates %s   arms %s   dt %s"
          % (len(rows), len({r["cell"] for r in rows}),
             sorted({r["replicate"] for r in rows}), arms, dts))
    bad_rc = [r for r in rows if r["rc"] != 0]
    if bad_rc:
        print("WARNING: %d rows with rc != 0" % len(bad_rc))
    for thr, tag in ((BAD_THRESHOLD_KJ, "PRIMARY"), (SECOND_THRESHOLD_KJ, "secondary")):
        print("\n=== %s: fraction of trajectories with max per-step |dEpot| >= %g kJ/mol ==="
              % (tag, thr))
        for dt in dts:
            sub = [r for r in rows if r["dt_fs"] == dt]
            by_cell = {}
            for r in sub:
                by_cell.setdefault(r["cell"], {}).setdefault(r["replicate"], {})[r["arm"]] = \
                    r["max_step_kj"]
            print("\n dt = %g fs   (n = %d trajectories per arm)"
                  % (dt, sum(1 for r in sub if r["arm"] == REFERENCE_ARM)))
            print("  %-16s %7s %6s   %-18s   %-24s  %8s   %9s %8s %8s %8s"
                  % ("arm", "bad", "p", "p 95% CI (cluster)", "dp vs mg [95% CI]",
                     "McNemar", "median", "p90", "p99", "max"))
            for arm in arms:
                vals = [r["max_step_kj"] for r in sub if r["arm"] == arm]
                if not vals:
                    continue
                nbad = sum(1 for v in vals if v >= thr)
                p = nbad / len(vals)
                ps, dd = cluster_bootstrap(by_cell, arm, REFERENCE_ARM, a.draws, rng, thr)
                pci = (quantile(ps, 0.025), quantile(ps, 0.975))
                if arm == REFERENCE_ARM:
                    dtxt, mc = "  (reference)", ""
                else:
                    dci = (quantile(dd, 0.025), quantile(dd, 0.975))
                    dp = p - sum(1 for r in sub if r["arm"] == REFERENCE_ARM
                                 and r["max_step_kj"] >= thr) / \
                        max(1, sum(1 for r in sub if r["arm"] == REFERENCE_ARM))
                    star = "*" if (dci[0] > 0 or dci[1] < 0) else " "
                    dtxt = "%+.4f [%+.4f,%+.4f]%s" % (dp, dci[0], dci[1], star)
                    b = c = 0
                    for cell, reps in by_cell.items():
                        for rep, d in reps.items():
                            if arm in d and REFERENCE_ARM in d:
                                x, y = d[arm] >= thr, d[REFERENCE_ARM] >= thr
                                b += x and not y
                                c += y and not x
                    mc = "p=%.3g" % binom_two_sided(b, c)
                print("  %-16s %3d/%-4d %6.4f   [%.4f,%.4f]   %-24s  %8s   %9.1f %8.1f %8.1f %8.1f"
                      % (arm, nbad, len(vals), p, pci[0], pci[1], dtxt, mc,
                         quantile(vals, 0.5), quantile(vals, 0.9), quantile(vals, 0.99),
                         max(vals)))
    print("\n=== secondary: events, rebuild tail, T_max ===")
    for dt in dts:
        sub = [r for r in rows if r["dt_fs"] == dt]
        print("\n dt = %g fs" % dt)
        print("  %-16s %10s %10s %10s %10s %10s %10s"
              % ("arm", "ev>=50/ps", "traj w/ev", "rebuilds", "maxjump", "njump>=50", "T_max"))
        for arm in arms:
            s = [r for r in sub if r["arm"] == arm]
            if not s:
                continue
            ps_ = sum(r["duration_ps"] for r in s)
            print("  %-16s %10.3f %9.3f%% %10d %10.1f %10d %10.0f"
                  % (arm, sum(r["n_ge50"] for r in s) / max(ps_, 1e-9),
                     100.0 * sum(1 for r in s if r["n_ge50"] > 0) / len(s),
                     sum(r["rebuilds"] for r in s), max(r["max_jump_kj"] for r in s),
                     sum(r["n_jump_ge50"] for r in s), max(r["t_max_k"] for r in s)))
    print("\n=== failing-cell overlap (a cell FAILS for an arm if >=1 of its replicates is bad"
          " at the %g kJ/mol threshold) ===" % BAD_THRESHOLD_KJ)
    for dt in dts:
        sub = [r for r in rows if r["dt_fs"] == dt]
        fails = {}
        for arm in arms:
            fails[arm] = {r["cell"] for r in sub
                          if r["arm"] == arm and r["max_step_kj"] >= BAD_THRESHOLD_KJ}
        print("\n dt = %g fs   " % dt +
              "  ".join("%s:%d" % (a_, len(fails[a_])) for a_ in arms))
        for arm in arms:
            if arm == REFERENCE_ARM or not fails[arm]:
                continue
            inter = fails[arm] & fails[REFERENCE_ARM]
            union = fails[arm] | fails[REFERENCE_ARM]
            print("   %-16s shared with mg %2d / union %2d (Jaccard %.2f); only-%s: %s"
                  % (arm, len(inter), len(union), len(inter) / max(1, len(union)), arm,
                     ",".join(sorted(fails[arm] - fails[REFERENCE_ARM])[:8]) or "-"))
        if fails.get(REFERENCE_ARM):
            others = set().union(*[fails[a_] for a_ in arms if a_ != REFERENCE_ARM]) \
                if len(arms) > 1 else set()
            only = sorted(fails[REFERENCE_ARM] - others)
            print("   %-16s only-mg cells: %s" % ("mg", ",".join(only[:8]) if only else "-"))
        allcells = sorted(set().union(*[fails[a_] for a_ in arms])) if arms else []
        for c in allcells:
            print("     %-18s %s" % (c, " ".join("%s:%s" % (a_, "X" if c in fails[a_] else ".")
                                                 for a_ in arms)))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("anchor")
    s.add_argument("--binary", required=True)
    s.set_defaults(fn=cmd_anchor)

    s = sub.add_parser("sweep")
    s.add_argument("--binary", required=True)
    s.add_argument("--out", required=True)
    s.add_argument("--arms", default="mg,mg2,mg3,gauss,gauss_delivered")
    s.add_argument("--dts", default="0.25,0.125,0.0625")
    s.add_argument("--replicates", type=int, default=5,
                   help="number of PERTURBED replicates; replicate 0 (unperturbed) is always run")
    s.add_argument("--maxtime", type=float, default=5000.0, help="true fs")
    s.add_argument("--jobs", type=int, default=8)
    s.add_argument("--cells", default="")
    s.add_argument("--scratch", default="")
    s.add_argument("--overwrite", action="store_true")
    s.set_defaults(fn=cmd_sweep)

    s = sub.add_parser("one")
    s.add_argument("--binary", required=True)
    s.add_argument("--cell", required=True)
    s.add_argument("--arm", required=True)
    s.add_argument("--dt", type=float, default=0.25)
    s.add_argument("--replicate", type=int, default=0)
    s.add_argument("--maxtime", type=float, default=5000.0)
    s.add_argument("--keep", default="")
    s.set_defaults(fn=cmd_one)

    s = sub.add_parser("analyze")
    s.add_argument("--csv", required=True)
    s.add_argument("--draws", type=int, default=10000)
    s.set_defaults(fn=cmd_analyze)

    a = ap.parse_args()
    sys.exit(a.fn(a) or 0)


if __name__ == "__main__":
    main()
